export * from './createCeleb';
export * from './getCelebById';
export * from './updateProfileById';
export * from './uploadProfliePicById';
export * from './getAllCelebs'
export * from './getAllCelebPicsById';
export * from './removeAllCelebPicsById';
export * from './removeCelebById';
export * from './getCelebPlaysById';
export * from './getCelebPicByUrl';
export * from './removeCelebPicByUrl';
export * from './removeProfilePicById';
export * from './uploadCelebPicsById';
